apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: vote-app
data:
  AWS_REGION: ap-south-1                 # change if needed
  VOTES_BUCKET_NAME: simple-vote-app-data    # <- PUT your real S3 bucket name
  VOTES_OBJECT_KEY: vote_counts.json
